### ISSUE TITLE
Tor on Campus

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#1]
**Related to:** Tor & EFF
**Activity Link:** https://www.eff.org/torchallenge/tor-on-campus.html

**General Activity Description (what do people do):**
Students advocate to their universities to have a Tor node installed on their campus.  

**Why does this matter/should people do this:** 
- It is a meaningful contribution towards our project of a free, safe, and globally connected Internet.
- Learning opportunity 

**Description for site:** Help anonymized internet connections travel faster so that people can use the Internet safely and more efficiently, by advocating for a Tor node on your university and college campuses

**Suggested Goals:** 
[Key Performance Indicators]
- was a tor node added to your campus

**Comment by LucyeoH** [comment]
Image: 
![screen shot 2016-11-07 at 1 52 30 pm](https://cloud.githubusercontent.com/assets/8070833/20071211/78535b6e-a4f1-11e6-9082-0aa507f53eb5.png)
