### ISSUE TITLE
IoT Build Event 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#10]
## **Tell Us About Your Activity**

**Related to:**
[Campaign/Org/Program]

**Activity Link:** 
[External Link]

**General Activity Description what do people do:**
[Describe what people have to do in this activity]

**Why does this matter/should people do this:** [How does this benefit the free and open web]
## **Info for the Website**

**Description for site:** 

**Suggested Goals:** 
[Key Performance Indicators]
-  
- 
-

**Comment by DineshMv** [comment]
Can I help for this issue?

**Comment by LucyeoH** [comment]
@DineshMv for sure! We don't have a team building this activity right now so if you have an idea for an activity in this area please submit it!

**Comment by DineshMv** [comment]
Thank you @LucyeoH , I will update few activity proposals soon.

**Comment by dvigneshwer** [comment]
@LucyeoH @DineshMv  check this out (https://goo.gl/JxDic1) and let me know your feedbacks, it's an event kit for getting started with IOT skills.
