### ISSUE TITLE
Fight to Change Copyright 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#11]
## **Tell Us About Your Activity**

**Related to:**
Maker Party 

**Activity Link:** 
https://www.changecopyright.org/

**General Activity Description what do people do:**
Share information about copyright reform in their communities and gather signatures for the petition. 

**Why does this matter/should people do this:** 
A key part of what makes the internet awesome is the principle of innovation without permission — that anyone, anywhere, can create and reach an audience without anyone standing in the way. That key principle is under threat. Some people are calling for licensing fees and restrictions on Internet companies for basic things like creating hyperlinks or uploading content. Others are calling for new laws that would mandate monitoring and filtering online. These changes would establish gatekeepers and barriers to entry online, and would risk undermining the internet as a platform for economic growth and free expression.

We need to defend the principle of innovation without permission in copyright law. Abandoning it by holding platforms liable for everything that happens online would have an immense chilling effect on speech, and would take away one of the best parts of the internet — the ability to innovate and breathe new meaning into old content.
## **Info for the Website**

**Description for site:** 
The power of the internet lies in its openness — the web is a level playing field where everyone can create, share, remix, and express themselves

But in the European Union, the current copyright legal framework undermines this trait. Help keep the web open by rallying your campus around the campaign for copyright reform. 

By doing so, we can shift this debate and harness this once in a generation moment to make a real difference by enacting progressive, modern reform of copyright law in the EU.

Tags: 
     Awareness
     Action

**Suggested Goals:** 
-  # of attendees at presentation
-  # of signatures
-

**Comment by LucyeoH** [comment]
Measures: 
# of attendees at event
# of signatures

Can cross-compare with Maker Party website

**Comment by LucyeoH** [comment]
Image: 
![screen shot 2016-11-07 at 1 51 42 pm](https://cloud.githubusercontent.com/assets/8070833/20071188/5a459c04-a4f1-11e6-80fd-16e145957368.png)
