### ISSUE TITLE
Hack on Prototyped Ideas from TBTW

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#12]
## **Tell Us About Your Activity**

**Related to:**
[Campaign/Org/Program]

**Activity Link:** 
[External Link]

**General Activity Description what do people do:**
[Describe what people have to do in this activity]

**Why does this matter/should people do this:** [How does this benefit the free and open web]
## **Info for the Website**

**Description for site:** 

**Suggested Goals:** 
[Key Performance Indicators]
-  
- 
-

**Comment by Mte90** [comment]
It's not a bad idea but I guess that is required to do a list of the prototype.
In the case of mine (https://github.com/Mte90/how-many-resources) it's working with few improvements during the months.
I think that this one can be useful to promote webextensions and also about privacy concerns.
