### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#13]
## **Tell Us About Your Activity**

**Related to:**
Github, open source hacking!

**Activity Link:** 
https://hacktoberfest.digitalocean.com/

**General Activity Description what do people do:**
People are going to hack on open source projects and submit them!

**Why does this matter/should people do this:**
Brings more contributions to open source projects!
## **Info for the Website**

**Description for site:** 

**Suggested Goals:** 
[Key Performance Indicators]
-  50 new open source contributions
- 
-

**Comment by Mte90** [comment]
I guess that is passed :-/
