### ISSUE TITLE
GitHub's November Game Off 2016

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#18]
**Tell Us About Your Activity**

https://github.com/github/game-off-2016
- 

**Related to:**
GitHub & Open Soure

**Activity Link:** 
https://github.com/github/game-off-2016

**General Activity Description what do people do:**
You have the entire month of November to create a game loosely based on the theme hacking, modding and/or augmenting.

What do we mean by loosely based on hacking, modding and/or augmenting? We literally mean, loosely based. Some examples might be:

    * an endless runner where you hack down binary trees in your path with a pixelated axe,
   *  a modern take on a classic e.g. a roguelike set in a 3D or VR world, or
    * an augmented reality game bringing octopus/cat hybrids into the real world.

Unleash your creativity. You can work alone or with a team and build for any platform or device. The use of open source game engines and libraries is encouraged but not required.

**Why does this matter/should people do this:**
Keep the web open through open gaming! Game designers and players who embrace open gaming believe that sharing, transparency, and rapid prototyping can lead to superior entertainment experiences. Learn more about open gaming [here](https://opensource.com/resources/what-open-gaming). 

**Info for the Website**
You have the entire month of November to create a game loosely based on the theme hacking, modding and/or augmenting.

Unleash your creativity. Work with your club and open source game engines and libraries to build for the world of open gaming! 

**Suggested Goals:** 

* Game submitted to GitHub  

Image: 
![screen shot 2016-11-07 at 1 40 19 pm](https://cloud.githubusercontent.com/assets/8070833/20070795/caa8ef02-a4ef-11e6-940d-6421d83450e5.png)

**Comment by LucyeoH** [comment]
@bacharakis any clever ways you can think of to track clubs who are participating? 

Ideas: 
* Can we have them pull to an org repo that's ours? 
* Can we ask GitHub to see if they can help us build something into the submission form that asks ppl if they're part of a Mozilla Club? 
* Can we ask all Mozilla Club Members to indicate they're part of a Mozilla Clubs in their GitHub repos? 
* Do we just rely on self-report on the forms?
