### ISSUE TITLE
Web compatibility proposal [DRAFT]

### ISSUE THREAD

**Issue by bacharakis** [mozilla/Campus-Activities#19]
**Tell Us About Your Activity**
- An activity to report or diagnose web compatibility issues

**Related to:**
[Campaign/Org/Program]

**Activity Link:** 
https://webcompat.com/

**General Activity Description what do people do:**
Report a bug for any website or browser.

**Why does this matter/should people do this:** [How does this benefit the free and open web]

**Info for the Website**
- Webcompat.com is a gathering place for the web compatibility community. This site is a place to report bugs from any website across the web - whether you are a developer or not. Started by the Mozilla Web Compatibility team, this initiative is a global task force on a mission to improve the web one bug at a time. Join us! Let's work together to make the web a better place to work and play. 

**Description for site:** 

**Suggested Goals:** 
[Key Performance Indicators]
*  
* 
*

**Comment by felipez3r0** [comment]
I'm working on that! 👍
