### ISSUE TITLE
Meme Around

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#2]
## **Tell Us About Your Activity**

**Related to:**
Maker Party

**Activity Link:** 
https://chadsansing.github.io/eu-maker-party-sample-activites/updated-eu-maker-party-content/activity02-meme-around.html#overview

**General Activity Description what do people do:**
In this activity you’ll engage your group in creating memes that support copyright reform! You’ll show the group how to use their own pictures or pictures from the public domain to speak up without breaking the current copyright laws that make it so difficult to create and share memes in the EU. 

**Why does this matter/should people do this:** [How does this benefit the free and open web]
We need common-sense copyright reform to include a universal exemption for fair dealing / fair use - or something like it - that would help protect examples of reuse like memes across the EU.
## **Info for the Website**

**Description for site:** 
Engage a group in creating memes that support copyright reform through making as a politicail act! You’ll show the group how to use their own pictures or pictures from the public domain to speak up without breaking the current copyright laws that make it so difficult to create and share memes in the EU. 

**Suggested Goals:** 
[Key Performance Indicators]
-  
- 
-

**Comment by LucyeoH** [comment]
Image: 
![45922429](https://cloud.githubusercontent.com/assets/8070833/20071305/f5cde078-a4f1-11e6-9ce0-700a2438667f.jpg)
