### ISSUE TITLE
December Build Activity - 24 Pull Requests of Christmas

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#22]
**Tell Us About Your Activity**

 _24 Pull Requests is a little project to promote open source collaboration during December._

_The idea is basically "Send 24 pull requests between December 1st and December 24th", encouraging developers to give back to open source with little gifts of code throughout December._ 

**Related to:**
Open Source: 24pullrequests.com

**Activity Link:** 
http://24pullrequests.com/

**Info for the Website**
 This December why not give back to the open source community with little gifts of code? 

Contributing to open source projects is a great way to build your profile in the community and improve your CV. Even small contributions can be really valuable to a project. Now is the time to say thanks to the maintainers of those projects, and a little birdy tells me that they love receiving pull requests! 

**CTA** 
Give The Gift of Code!
[Link](https://github.com/login?client_id=338f3c32152479f1251d&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3D338f3c32152479f1251d%26redirect_uri%3Dhttp%253A%252F%252F24pullrequests.com%252Fauth%252Fgithub%252Fcallback%26response_type%3Dcode%26state%3D1316355a3a389f4b55c7d152f907b22b14ec68e0eb95c5b3): Can we have this send them directly to the login with GitHub page? 

**Suggested Goals:** 
*# of contributions to one open source project
*# of projects contributed to 
*Throw a 24 Pull Requests hack events

**Comment by LucyeoH** [comment]
![24pullrequests](https://cloud.githubusercontent.com/assets/8070833/20719669/9a0c1256-b62a-11e6-99bb-ee8e9eee34c2.png)
