### ISSUE TITLE
World is here this is open source 

### ISSUE THREAD

**Issue by Prince8791** [mozilla/Campus-Activities#23]
**Tell Us About Your Activity**
- 

**Related to:**
[Campaign/Org/Program]

**Activity Link:** 
[External Link]

**General Activity Description what do people do:**
[Hi I am thinking about open source program how we can extend all over the world how every people know about what is actually open source last month I met with too many peoples and discuss about open source but they do not know about the that. And I am the thing about what is the think for success for open source how everyone knows about that. the idea is there we can start from lower level like small university and need to launch one course which whole about open source.

**Why does this matter/should people do this:** [How does this benefit the free and open web]

**Info for the Website**
- 

**Description for site:** 

**Suggested Goals:** 
[Key Performance Indicators]
*  
* 
*

**Comment by LucyeoH-zz** [comment]
@Prince8791 hey! I wonder if the activity we create around this is an open source advocacy piece that provides students with some tools to talk about and promote open source on their campus. Thoughts? Do you have any tools you use for this that you'd recommend?

**Comment by Prince8791** [comment]
**@LucyeoH** Yes You are right its battery for learning the purpose and that is really good for the student but I don't have any open source tool but I have a good strategy and plans for learning open source and I have the platform where students can learn easily and then done his lab practical there. and if you what to recommend me. I would like to  accept your purpose.

**Comment by Prince8791** [comment]
Yes You are right its battery for learning the purpose and that is really
good for the student but I don't have any open source tool but I have a
good strategy and plans for learning open source and I have the platform
where students can learn easily and then done his lab practical there. and
if you what to recommend me. I would like to accept your purpose.
