### ISSUE TITLE
HTML game development

### ISSUE THREAD

**Issue by rakesh-chinta** [mozilla/Campus-Activities#24]
**Tell Us About Your Activity**
- As the initiation of the Mozilla campus club, we are gonna do a university-based HTML coding event where we create games based on HTML , and web modules for a long duration of 2 weeks, all the results will be submitted on my page to be forked by the Mozilla official account on GitHub.

**Related to:**
[HMTL5 hackathon/Mozilla campus Event ]

**Activity Link:** 
[www.hubstrike.com ; www.github.com/rakesh-chinta]

**General Activity Description what do people do:**
  2-week university hackathon
* 500+ student based open source contribution
* Introduction and orientation of Github and open source to a whole new community of students and enthusiasts.

**Why does this matter/should people do this:** [How does this benefit the free and open web]
Introduction and orientation of Github and open source to a whole new community of students and enthusiasts.

**Info for the Website**
- https://mozillacampusclubs.github.io/HTML-5-Game-Development/

**Description for site:** 
Official Mozilla campus event 
**Suggested Goals:** 
[Key Performance Indicators]
*  2-week university hackathon
* 500+ student based open source contribution
* Introduction and orientation of Github and open source to a whole new community of students and enthusiasts.

**Comment by bacharakis** [comment]
Hi there!

This is a repository for proposing new activities which are not already in the website. 
You will have the opportunity report your club's activities at the end of the month through the relevant form which will be e-mailed to you.

thank you so much for your passion and effort.
