### ISSUE TITLE
Winter Season of Code

### ISSUE THREAD

**Issue by rjrajivjha** [mozilla/Campus-Activities#28]
**Tell Us About Your Activity**
- Winter Season of code, is an open source coding event which will expect proposal from students over some listed projects which either align with the mission of mozilla or the respective mozilla club, it can be of university, state, national or international importance.

**Related to:**
[Campaign/Org/Program]
-Build the Open web

**Activity Link:** 
[External Link]
Registration Form of this type 
-http://tinyurl.com/ipusoc

**General Activity Description what do people do:**
[Describe what people have to do in this activity]

-Students are free to propose their own project under winter season of code.
- Each club can run a separate WSOC at university level or join us by promoting it over their campus.
- Club captain is free to decide its time-line or follow the one proposed by *wings of fire*.
- Get the proposal from students.
- Proposed Time line : 
Registration Starts - November 26, 2016
Registration Ends - December 15, 2016
Project Proposal Deadline - December 20, 2016

< Prototype of the proposal, just for referral purpose, students are free to chose a different pattern :  https://docs.google.com/document/d/1aCQGQk10KnOd_WSBv2ZzUeEOO975LBq12LoXatnbIfU/edit?usp=sharing >

Selected candidates with projects will be announced on December 24, 2016.
Meet with mentors and Discussion on Projects - December 25th  -31st 2016
Coding starts - January 1st 2017
Mid - Evaluation Period :  January 10-13  2017
Coding Ends - January 23rd 2017
Project Submission Deadline - January 24th 2017
Results - January 26th 2017

SUCCESSFUL SUBMISSIONS CAN BE AWARDED WITH EXCITING PRIZES, SWAGS AND GOODIES.

**Info for the Website**
- Run a winter season of code over your campus and get people coding for the open web.

**Description for site:** 
-  Time-line, Registration form and email for proposal will do the job. 

**Call To Action:**
[What should the button say? i.e. Get Started, Start Hacking]
Submit Proposal
**Suggested Goals:** 
[Key Performance Indicators]
*   No. of Expected Participants : #200
*   No. of New Rust Developer : #25
*   No. of New A-Frame JS Developer ; # 25 <as a project can have maximum of 5 Team>

 
_Please suggest an image or graphic for this activity in the comments below._

https://lh4.googleusercontent.com/iW3l3LAcgpuzsT3iUR1yYcqko788rSobT6o8pKOBEeQYV8UYJX7StpZXmpZea240b0tXnoVUcQ=w1237

**Comment by bacharakis** [comment]
Hi there and thank you so much for the proposal! Can you please share more information on what Winter season of code is exactly and what students are invited to do?

Thank you

**Comment by championshuttler** [comment]
Winter Season of Code actually a winter program of Coding something like that of GSoC where the university students have to made some of open source Software, Websites, Apps for Mobile in the time of their College break of Winter
U can find more details about the projects at https://shivams2799.github.io/wsoc/

Thank You
