### ISSUE TITLE
Raise awareness of Tracking, Cyber Security & Government Surveillance

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#3]
## **Tell Us About Your Activity**

**Related to:**
Maker Party 

**Activity Link:** 
https://d157rqmxrxj6ey.cloudfront.net/mozstacy/21938/
https://learning.mozilla.org/en-US/activities/privacy-basics/

**General Activity Description what do people do:**
Teach your community how to safeguard their privacy online and develop an awareness of how companies and governments track and collect their data online.

**Why does this matter/should people do this:** Understanding the threats to privacy online is key to people being able to take full advantage of the resource as a global public resource.
## **Info for the Website**

**Description for site:** 

Raise awareness of Tracking, Cyber Security & Government Surveillance

Throw a workshop to help spread awareness of the threats to people’s privacy and security online.

Tags:

```
Awareness
Safe
```

**Suggested Goals:** 
[Key Performance Indicators]
    # of events
    # of attendees

**Comment by LucyeoH** [comment]
Image: 
![topic-think-deeper 2d1fbc329611](https://cloud.githubusercontent.com/assets/8070833/20071414/6d1e47e4-a4f2-11e6-8ebf-456f9b920121.png)
