### ISSUE TITLE
Build your Club's information page

### ISSUE THREAD

**Issue by bacharakis** [mozilla/Campus-Activities#30]
**Tell Us About Your Activity**
- Build your Club's information page by learning git and how to use github pages.

**Related to:**
[Campaign/Org/Program]

**Activity Link:** 
https://pages.github.com/

**General Activity Description what do people do:**
It's required to have completed the two "Learn" activities relevant to git and github. 
Then, by going through this activity you will have a website where you can include your club's information like location, club captain, contact information, number of members etc. 
The activity will be using a template similar to the HTML5 game development template.

**Info for the Website**
- 

**Description for site:** 

**Call To Action:**
[What shoudl the button say? i.e. Get Started, Start Hacking]

**Suggested Goals:** 
[Key Performance Indicators]
*  
* 
* 
_Please suggest an image or graphic for this activity in the comments below._

**Comment by Mte90** [comment]
Uhm maybe create also a github organization?

**Comment by bacharakis** [comment]
This organization? https://github.com/mozillacampusclubs :P

**Comment by Mte90** [comment]
I think that every clubs need to have their organization in that way in their org they can have a repo like mozunicampus.github.io that is a real website with the gh-pages.

**Comment by bacharakis** [comment]
I love decentralization but we need to have a way to gather all of our clubs contributions in one place. And I think different repos in the same org can support that.

**Comment by Mte90** [comment]
I know that a repo name in a format {organization}.github.io you get the domain but I am not sure that you can do a repo name on a format {organization}-club1.github.io and get a website

**Comment by bacharakis** [comment]
But you can do: mozillacampusclubs.github.io/bariclub ;) Right?

**Comment by Mte90** [comment]
Uhm I don't think that leave an access to an unique repo for all the club will be a good idea. 
Who can approve the changes? 
What is the delay to get an approval of the pr? 
Who check the pr that do only changes in a specific folder?

**Comment by bacharakis** [comment]
Well, learning these things help you contribute to Open Source projects right? In any case this is still a proposal and we would love to get alternatives and feedback.

**Comment by Mte90** [comment]
Learn this things sure but if will be the official page for the clubs can be a problem of management.
In that case it's better a specific repo for mess things in their profile so not all the clubs pages can get problems.
