### ISSUE TITLE
How to do a WebExtension

### ISSUE THREAD

**Issue by Mte90** [mozilla/Campus-Activities#31]
**Tell Us About Your Activity**
Webextension are cool and very easy to do. An hackaton is very simple with a theme :-)

**Activity Link:** 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**General Activity Description what do people do:**
* Try the examples available from mdn
* Develop an extension
* Show to the others what they done
* Maybe publish after the event on amo

**Info for the Website**
- 

**Description for site:** 

**Call To Action:**
Let's do it a browser extension

**Suggested Goals:** 
* Finish the extension (not only a prototype)
* Publish on amo

**Comment by tsl143** [comment]
Adding to that, 
1. we can collect Ideas from participants for new addons.
2. We can also start with referring chrome extensions and converting them to web extensions.

**Comment by Mte90** [comment]
For the second point i think it's better a greasemonkey script that is more easy to convert respect a full extension. Also the chrome extension works on firefox but firefox don't cover all the apis actually.

**Comment by tsl143** [comment]
Actually.
Btw I was unaware of greasemonkey script, Just reading it :)
