### ISSUE TITLE
Learn Arduino Together

### ISSUE THREAD

**Issue by marcs7** [mozilla/Campus-Activities#35]
**Tell Us About Your Activity**
-Discover an open source project called Arduino through extensive simple activities
[External link]
https://github.com/MarS7/Learn-Arduino (in update)

**Related to:**
[Program]
-Build 
-Teach
**Activity Link:** 
Club captain will generate a form  

**General Activity Description what do people do:**
The activity will be divided in two parts:
1)theoretical part: in this part we will explain how arduino work and some simple commands
2)practical part: in this part we will show what seen in theory and applied using arduino boards

**Call To Action:**
Let's make something open source 

**Suggested Goals:** 
[Key Performance Indicators]
*  Build some simple project
* Programming arduino boards 
* Know what can do with Arduino

**Comment by Mte90** [comment]
In my experience I think that we need to specify what type of arduino and components is required and also code already available and highly commented with photos.
As I that are already available 2 lessons, good job!
I think that something with a potentiometer and a buzzer can be funny, I remember that I done the supermario tune with the buzzer and a potentiometer to speed up the music.

**Comment by marcs7** [comment]
Is possible to use any arduino for simple activities like that. For the components i have all available in my little home laboratory. Code is on github and is update every time I check that I have the material required.
