### ISSUE TITLE
Python Sprint

### ISSUE THREAD

**Issue by GVRGowtham** [mozilla/Campus-Activities#36]
**Tell Us About Your Activity**

**Python Sprint:**

Python is a multi-purpose programming language that has a huge impact on the fields on Machine Learning, Web development, Automation, Testing, Internet of Things, Application development and much more. Mozilla uses python for web development, generating code (lots and lots of them), automation and much more. So why not learn python and contribute?

Long story short, this activity is a two-week long sprint for people who are interested in coding. There should be a team of people from the campus club who are familiar with the python class's agenda and content. We can train a group of people from the college campus before they handle sessions. At the end of this activity, people would be familiar enough with python so that they can kick start their contributions.

**Related to:**

Program

**Activity Link:** 

Github repo reference : https://github.com/GVRGowtham/Python-Class [still in updating, online sprint in going on :) ]
Website : https://gvrgowtham.github.io/Python-Class/index.html

**General Activity Description what do people do:**

People will be taught python basics on one hour/day for three days/week. These three days will be alternating days to ensure people are not stuffed. There will be tasks provided for the participants to do. Say there is a session on Monday, at the end of the session a task or a problem will be provided to the participants. They will have to submit the task before the next session comes (i.e) Wednesday. This continues for two weeks. We have a time table and resources ready for people to take and do the activity.

Day 0 - Introduction to Github 
Day 1 - Basic programming concepts  ( They will programming on the languages they are familiar with )
Day 2 - Programming using python
Day 3 - A look into classes, how to share classes between python files and use of stack and queues in python
Day 4 - File handling, system calls and OS navigation, ...
Day 5 - API basic usage (Numpy, date, time, etc...)
Day 6 - Development of custom classes APIs

Project - Prepare a code using all the concepts taught

Once all the sessions are over, we will introduce python based contribution. Automation, testing, web development and lot more contributions are welcomed in python. Depending on the participant's interests, they will be redirected to the particular team to get resources and complete the training. Once that's over, people can contribute using python.

**Info for the Website**

Well, the website link is above which is a open repo. People can fork that repo, edit it for their college and have a website that showcases their campus club's python sprint activity.

**Description for site:** 

Refer the sample site: https://gvrgowtham.github.io/Python-Class/index.html

**Call To Action:**

Get Started. Download the kit and kick start with python.

**Suggested Goals:** 

*  Number of contributions in testing area
*  Generating automation code
*  Similar...

**Comment by GVRGowtham** [comment]
This sprint is organized by myself and @prasanthp96

**Comment by bacharakis** [comment]
Hi @GVRGowtham and thank you so much for sharing this!

This repo is for people to share ideas for activities they are interested to see as part of the Campus Clubs program which will help students to get more skills and contribute to open source projects.

Are you sharing this activity with us because you want to see it as part of the Campus Clubs Activities or because you want to inform us about the great work you are doing?

Looking forward for your reply.
Cheers

**Comment by GVRGowtham** [comment]
Hey @bacharakis,

I would love to see this activity as a part of Campus Clubs and we would like to volunteer for providing the resources and mentoring the activity, if its possible. 

Cheers.
