### ISSUE TITLE
Contribute Photos to the Commons 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#4]
## **Tell Us About Your Activity**

**Related to:**
Maker Party 

**Activity Link:** 
https://chadsansing.github.io/eu-maker-party-sample-activites/updated-eu-maker-party-content/activity03-contribute-to-the-commons.html

**General Activity Description what do people do:**
Help people understand the commons’ value - content we can all use freely in our lives and work, by contributing to it.

**Why does this matter/should people do this:** The commons is a free and public resource that is important to creativity and innovation online. Fighting out of date copyright laws. 
## **Info for the Website**

**Description for site:** 
We all deserve better than a stock world, and the more high-quality photos there are in the public domain for blog and website owners to use, the more open and beautiful the Web will be.

Tags:

```
Participate
Awareness
```

**Suggested Goals:** 
- # of photos contributed to the Commons
-  of events
-  # of attendees
-  # of petitions signed

**Comment by LucyeoH** [comment]
Image: ![6a94c428-1032-4a99-aa35-5ebddf285cd5](https://cloud.githubusercontent.com/assets/8070833/20071287/dc59cdd2-a4f1-11e6-9fe5-d51736bcefd4.png)
