### ISSUE TITLE
Learn A New Programming Language: Rust

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#5]
## **Tell Us About Your Activity**

**Related to:**
Rust

**Activity Link:** 
https://mozilla.github.io/activate.mozilla.community/developer-engagement/rust-hack/

**General Activity Description what do people do:**
The Rust programming language will be important to the future of the web, making it safe and great. Having more developers understand, use and evangelize this language will advance make the web better and more secure.

**Why does this matter/should people do this:** [How does this benefit the free and open web]
## **Info for the Website**

**Description for site:** 
The Rust programming language will be important to the future of the web, making it safe and great. Having more developers understand, use and evangelize this language will advance make the web better and more secure.

Tags:
    Open
    Write

**Suggested Goals:** 
* # of events
*  blog post
*  # of new people signed up to the Rust developer list

**Comment by LucyeoH** [comment]
Image options:

 
![v7txhrjp9pdqrkdtxxp0](https://cloud.githubusercontent.com/assets/8070833/20072064/028b340c-a4f5-11e6-878f-499d6bdbb06f.png)

OR

![cvykel1xeaaiucn jpg_large](https://cloud.githubusercontent.com/assets/8070833/20072114/2aa6da4a-a4f5-11e6-980e-77ed19d48b43.jpg)
OR
![cu7i32cukaazcvd](https://cloud.githubusercontent.com/assets/8070833/20072120/2fd779f2-a4f5-11e6-838d-ee68f990f452.jpg)

**Comment by dvigneshwer** [comment]
Created a lesson for getting started with rust at https://github.com/mozillascience/studyGroupLessons/tree/master/Rust-intro
