### ISSUE TITLE
Build for Virtual Reality 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#6]
## **Tell Us About Your Activity**

**Related to:**
VR

**Activity Link:** 
https://aframe.io/

**General Activity Description what do people do:**
Help bring a new kind of open technology to the web by using markup to create virtual reality experiences that work across desktop, iOS, Android, the Oculus Rift, and the HTC Vive.

**Why does this matter/should people do this:** Building open into the future of the internet. 
## **Info for the Website**

**Description for site:** 
Help bring a new kind of open technology to the web by using markup to create virtual reality experiences that work across desktop, iOS, Android, the Oculus Rift, and the HTC Vive.

Tags:

```
Open
Participate
```

**Suggested Goals:** 
- # makes
-

**Comment by LucyeoH** [comment]
Image Options:
![screen shot 2016-11-07 at 2 24 23 pm](https://cloud.githubusercontent.com/assets/8070833/20072338/f73b478a-a4f5-11e6-86af-15f116891c0b.png)

OR 
![mozilla-a-frame-webvr-virtual-reality-firefox](https://cloud.githubusercontent.com/assets/8070833/20072440/5f939990-a4f6-11e6-8d89-5d1c031c715e.png)
