### ISSUE TITLE
PostCrimes for Copyright

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#7]
## **Tell Us About Your Activity**

**Related to:**
Maker Party 

**Activity Link:** 
http://postcrimes.org/

**General Activity Description what do people do:**
In this activity you’ll engage your group in building virtual post-cards about outdated copyright laws that get printed out and sent to law-makers!

**Why does this matter/should people do this:** Reforming out of date copyright laws helps keep the internet open. 
## **Info for the Website**

**Description for site:** 
Help reform problematic copyright laws by making digital postcards and sending them to lawmakers. 

Tags: 

**Suggested Goals:** 
[Key Performance Indicators]
-  # of postcards made
-  # of postcards delivered
-

**Comment by LucyeoH** [comment]
Recommended Measures: 
- # of postcards made
- # of postcards delivered

Note: find out if we can verify on postcard site

**Comment by LucyeoH** [comment]
Update link: https://postcrimes.org/#!/

Image: 
![screen shot 2016-11-07 at 1 48 27 pm](https://cloud.githubusercontent.com/assets/8070833/20071060/e8f64cf6-a4f0-11e6-99c6-6159c524e1e4.png)

**Comment by LucyeoH** [comment]
Update link - http://postcrimes.org/
