### ISSUE TITLE
Innovation Toolkit

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Campus-Activities#9]
## **Tell Us About Your Activity**

**Related to:**
[Campaign/Org/Program]

**Activity Link:** 
[External Link]

**General Activity Description what do people do:**
[Describe what people have to do in this activity]

**Why does this matter/should people do this:** [How does this benefit the free and open web]
## **Info for the Website**

**Description for site:** 

**Suggested Goals:** 
[Key Performance Indicators]
-  
- 
-

**Comment by dvigneshwer** [comment]
Using this toolkit, we tried to solve a complex problem with a human-centric design process https://dvigneshwer.gitbooks.io/connecting-rural-women/content/ & https://dvigneshwer.wordpress.com/2016/11/26/solving-the-problem-of-connecting-rural-women/
